apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nucleus-api-storage-pvc
  namespace: pairbone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi
