apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: prediction-completed-nucleus
  namespace: pairbone
spec:
  topic: prediction_completed
  pubsubname: pubsub-rabbitmq
  routes:
    default: /subs/prediction-completed