apiVersion: v1
kind: Secret
metadata:
  name: nucleus-api-tls
  namespace: pairbone
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFMTCCBBmgAwIBAgISBcjN/T67KTFBxqhcM/XRPRQuMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    hd+uUkO2KibwNTvvMpk5OUU+aqZsPixlsjaMXJdGCewUlKCqEgP9hRbQv1ek8YMY
    rHxP45O2U4Za7KK5sF+hL4X/f8T4fo6sTWFcD/jmkKGKUQz9Qw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFBjCCAu6gAwIBAgIRAMISMktwqbSRcdxA9+KFJjwwDQYJKoZIhvcNAQELBQAw
    0zrLnOrAj/dfrlEWRhCvAgbuwLZX1A2sjNjXoPOHbsPiy+lO1KF8/XY7
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    CJB6TxkCgYEAm66YLK+wWy19jbP99zs2e+nuhIVnM+KqnA7qzX4FGmHcOENQpR8N
    mKMXXMgRyz7cyF4uuK9HV7XQEqwdGSUPwOOJnpd3YH5mm2tXPH8Bn/a5ac0Klvrc
    Xc3yHug6m/oXprWoDUcRX0m72sjcQ5BFiWCl8rrXD40n8Bn332lSUJk=
    -----END RSA PRIVATE KEY-----
